Heyuri/kokonotsuba

koko.php

Translated all the Chinese comments in koko.php to English for better code readability

Translated comments to English for code readability

---

koko.php

Improves speed by a few picoseconds

Small koko.php optimizations

---

koko.php

i'm bored, and since !(x >= y) is slower (by infinitesimal values)   i decided to replace it with x < y
praise lolico ill actually read up on the modules and actually contribute once im back from vacation

will this improve performance? barely

---

koko.php

It only applied renzoku for mods and not users... whoops ^^;

Fixed RENZOKU for users - koko.php Line 727

---

config.php

A pull request to add more fortunes for #14 
Thanks to @anonwaha for giving a list of fortunes, from both Sakamoto & previous Heyuri fortunes.
- Adds more fortune, allowing more variety for the fortune command
- Untested, but since it's just some extra strings in an array it's probably gonna work

More fortunes

---

config.php

Added comment about getting password hashes since I believe it is very important and is not listed anywhere.
This is for config.php

add important note about password hash

---

config.php
koko.php

- (Not a fix)
- Adds a constant in config.php for disabling/enabling sending saged posts to WHs
- Debian 10
- nginx
- MariaDB
- PHP 7.3

Add option for saged posts to be sent to WHs or not

---

config.php

As there is no documentation on how to do so in the README as well.

Add comment on how to use as textboard since it might not be self explanatory

---

koko.php

- Fixed tripcode encoding in koko.php
- Fixed tripcode encoding
- Debian 10
- nginx
- MariaDB
- PHP 7.3
- If you're unable to, just test it on your system, as in most cases it will work on Heyuri too

Fixed tripcode encoding

---

module/mod_countryflags.php

JS for a toggle flag button to be used on /jp/, commented out

Toggle flag button for /jp/

---

module/mod_bbcode.php

[scroll] tag for bbcode module

[scroll] tag

---

module/mod_adminban.php

closes #58 
This would also close the rangeban issue, since to my knowledge you can use global bans for that.

Ban list clearing fix

---

config.php
koko.php

TODO: remove old system that does this, without b0rking everything in the process

Age limit warning (1 line)

---

koko.php

You're able to upload huge files despite setting MAX_KB in config.php. Fixed

File size check

---

koko.php
module/mod_janitor.php

Mod improvements

---

module/mod_cat.php

- Debian 10
- nginx
- MariaDB
- PHP 7.3

thumbnails no longer get lost due to comprestion change

---

lib/thumb/thumb.gd.php

i made this commit yesterday but i guess i didnt pull it correctly? or pull at all. this works. and also get my other commit it fixes file extensions when change compression for catalog
- Debian 10
- nginx
- MariaDB
- PHP 7.3
If your pull request fits these requirements, you're ready to send it off![le cool yotsuba](https://static.heyuri.net/koko/image/emote/emo-yotsuba-cool.gi …

using jpg comprestion will convert background to reply color

---

koko.php

dear sirs:
I tested it, it works good
This allows moderators to select all checkboxes on a page for deletion in case of spam.
thank you
and much respect from india sir

Add "select all" button

---

static/css/base.css
static/css/futaba.css
static/css/heyuriclassic.css

- "codeblocks can create a huge horizontal scrollbar "
- "limits codeblock+msgbox width to screen"
- Debian 10
- nginx
- MariaDB
- PHP 7.3

[code] blocks make page too wide

---

config.php
koko.php
kokoimg.tpl
kokoimgreply.tpl
module/mod_search.php

Removes search() related stuffz from koko.php and moves it into a new module, mod_search.
reference issue: https://github.com/Heyuri/kokonotsuba/issues/72

search module

---

module/mod_movethread.php

quote linking is 'translated' over to the equivalent post number of the originally quote linked post.

quote links cross over

---

kokoimg.tpl
kokoimgreply.tpl
static/js/update.js

solves threads getting 'duplicated' when using js update

adjusting update.js to werk with new template

---

kokoimg.tpl
kokoimgreply.tpl

The container and reply div cannot have the same ID or else it b0rks.

fix highlighting

---

koko.php

Rebuilds only pages that are relevant when replying to a thread - issue #107

Rebuild only relevant pages

---

config.php

table is a keyword in sql. it should not be a keyword by defualt

changed varable name to something other then a keyword

---

koko.php
lib/lib_post.php

- Debian 10
- nginx
- MariaDB
- PHP 7.3

fix apostrophes in username

---

static/js/flashembed.js

apply img.js JS fix to here too

---

static/js/img.js

fix arrow keys not working in gallery mode.
vi keys was upside down so i fixed that too.

fix gallery mode hotkeys

---

koko.php
static/js/koko.js
static/js/qu.js

- Debian 10
- nginx
- MariaDB
- PHP 7.3

remove server-side quote

---

module/mod_cat.php

- Debian 10
- nginx
- MariaDB
- PHP 7.3

Fix catalog pagination

---

module/mod_cat.php

- Debian 10
- nginx
- MariaDB
- PHP 7.3

remember catalog sorting
